name: Robô Leilões Paraná

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  buscar-leiloes:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Rodar robô
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python scraper.py
