name: Robô Leilões Paraná

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
    inputs:
      aba:
        description: 'Qual aba processar?'
        required: true
        default: 'Pagina1'
        type: choice
        options:
          - Pagina1
          - Leiloeiros2
          - Leiloeiros3

jobs:
  buscar-leiloes:
    runs-on: ubuntu-latest
    timeout-minutes: 110
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - name: Rodar robô
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          ABA_LEILOEIROS: ${{ github.event.inputs.aba || 'Pagina1' }}
        run: python scraper.py
